export interface ProviderCapabilitiesConfig {
  search: boolean;
  metadata: boolean;
  directPlayback: boolean;
  hls: boolean;
  embed: boolean;
}

export interface ProviderRateLimitConfig {
  maxRequests: number;
  windowMs: number;
}

export interface ProviderDefinition {
  id: string;
  name: string;
  description: string;
  enabled: boolean;
  requiresKey: boolean;
  capabilities: ProviderCapabilitiesConfig;
  baseUrl: string;
  timeoutMs: number;
  rateLimit: ProviderRateLimitConfig;
  priority: number;
  latencyClass: 'fast' | 'medium' | 'slow';
}

/**
 * Returns dynamic configuration for all providers.
 * Key-dependent providers are dynamically evaluated based on environment variables.
 */
export function getProvidersConfig(): Record<string, ProviderDefinition> {
  const cleanYouTubeKey = process.env.YOUTUBE_API_KEY?.trim().replace(/^['"]|['"]$/g, '');
  const cleanPexelsKey = process.env.PEXELS_API_KEY?.trim().replace(/^['"]|['"]$/g, '');
  const hasYouTubeKey = Boolean(cleanYouTubeKey && cleanYouTubeKey.length > 5);
  const hasPexelsKey = Boolean(cleanPexelsKey && cleanPexelsKey.length > 5);
  const hasPixabayKey = Boolean(process.env.PIXABAY_API_KEY && process.env.PIXABAY_API_KEY.trim().length > 5);
  const hasVimeoToken = Boolean(process.env.VIMEO_ACCESS_TOKEN && process.env.VIMEO_ACCESS_TOKEN.trim().length > 5);

  return {
    youtube: {
      id: 'youtube',
      name: 'YouTube',
      description: 'Official YouTube Data API v3 with resilient direct gateway fallback',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://www.googleapis.com/youtube/v3',
      timeoutMs: 2500,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 100,
      latencyClass: 'fast',
    },
    dailymotion: {
      id: 'dailymotion',
      name: 'Dailymotion',
      description: 'Global video sharing platform with free public API search and responsive embeds',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://api.dailymotion.com',
      timeoutMs: 2000,
      rateLimit: {
        maxRequests: 100,
        windowMs: 60000,
      },
      priority: 95,
      latencyClass: 'fast',
    },
    openmovie: {
      id: 'openmovie',
      name: 'Open Cinema Vault',
      description: 'Iconic Creative Commons 4K cinematic films & open animation masterpieces',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://commondatastorage.googleapis.com',
      timeoutMs: 500,
      rateLimit: {
        maxRequests: 120,
        windowMs: 60000,
      },
      priority: 92,
      latencyClass: 'fast',
    },
    peertube: {
      id: 'peertube',
      name: 'PeerTube',
      description: 'Decentralized, open-source video network federated across community nodes',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: true,
        embed: true,
      },
      baseUrl: 'https://peertube.tv/api/v1',
      timeoutMs: 1200,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 95,
      latencyClass: 'fast',
    },
    vimeo: {
      id: 'vimeo',
      name: 'Vimeo',
      description: 'High-quality independent filmmaking & creator video network',
      enabled: hasVimeoToken,
      requiresKey: true,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://api.vimeo.com',
      timeoutMs: 1200,
      rateLimit: {
        maxRequests: 50,
        windowMs: 60000,
      },
      priority: 90,
      latencyClass: 'medium',
    },
    archive: {
      id: 'archive',
      name: 'Internet Archive',
      description: 'Public domain movies, historical footage, and cultural archive collections',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 40,
        windowMs: 60000,
      },
      priority: 85,
      latencyClass: 'medium',
    },
    pexels: {
      id: 'pexels',
      name: 'Pexels',
      description: 'Free HD & 4K stock footage with direct MP4 file playback',
      enabled: hasPexelsKey,
      requiresKey: true,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://api.pexels.com/videos',
      timeoutMs: 1200,
      rateLimit: {
        maxRequests: 50,
        windowMs: 60000,
      },
      priority: 80,
      latencyClass: 'medium',
    },
    pixabay: {
      id: 'pixabay',
      name: 'Pixabay',
      description: 'Royalty-free community stock video clips and nature footage',
      enabled: hasPixabayKey,
      requiresKey: true,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://pixabay.com/api/videos',
      timeoutMs: 1200,
      rateLimit: {
        maxRequests: 50,
        windowMs: 60000,
      },
      priority: 80,
      latencyClass: 'medium',
    },
    wikimedia: {
      id: 'wikimedia',
      name: 'Wikimedia Commons',
      description: 'Educational, scientific, and cultural public domain and Creative Commons video archive',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://commons.wikimedia.org/w/api.php',
      timeoutMs: 1500,
      rateLimit: {
        maxRequests: 40,
        windowMs: 60000,
      },
      priority: 75,
      latencyClass: 'medium',
    },
    nasa: {
      id: 'nasa',
      name: 'NASA Media',
      description: 'Official NASA space agency mission video broadcasts, rocket launches, and planetary probes',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://images-api.nasa.gov',
      timeoutMs: 1800,
      rateLimit: {
        maxRequests: 40,
        windowMs: 60000,
      },
      priority: 75,
      latencyClass: 'slow',
    },
    openverse: {
      id: 'openverse',
      name: 'Openverse',
      description: 'Creative Commons search index across openly licensed cultural media',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://api.openverse.org/v1',
      timeoutMs: 4000,
      rateLimit: {
        maxRequests: 40,
        windowMs: 60000,
      },
      priority: 70,
      latencyClass: 'slow',
    },
    livetv: {
      id: 'livetv',
      name: 'Live TV Channels',
      description: 'Free public news and documentary live stream feeds',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: true,
        embed: false,
      },
      baseUrl: 'local-feed',
      timeoutMs: 400,
      rateLimit: {
        maxRequests: 200,
        windowMs: 60000,
      },
      priority: 90,
      latencyClass: 'fast',
    },
    radio: {
      id: 'radio',
      name: 'Global Radio & Audio',
      description: 'Live broadcast audio streams and community radio directory',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://de1.api.radio-browser.info',
      timeoutMs: 1200,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 85,
      latencyClass: 'medium',
    },
    mux: {
      id: 'mux',
      name: 'Mux Video',
      description: 'High-performance HLS streaming & video analytics infrastructure (Free Developer Tier: 100,000 monthly delivery minutes)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: true,
        embed: false,
      },
      baseUrl: 'https://stream.mux.com',
      timeoutMs: 600,
      rateLimit: {
        maxRequests: 120,
        windowMs: 60000,
      },
      priority: 95,
      latencyClass: 'fast',
    },
    itunes: {
      id: 'itunes',
      name: 'Apple Music Videos',
      description: 'Official HD music videos, artist tracks, and podcasts with direct streaming playback',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://itunes.apple.com',
      timeoutMs: 1500,
      rateLimit: {
        maxRequests: 100,
        windowMs: 60000,
      },
      priority: 92,
      latencyClass: 'fast',
    },
    audius: {
      id: 'audius',
      name: 'Audius Music',
      description: 'Decentralized open streaming catalog with 1M+ independent artist tracks, electronic, hip-hop & remixes',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://api.audius.co',
      timeoutMs: 2000,
      rateLimit: {
        maxRequests: 80,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'medium',
    },
    somafm: {
      id: 'somafm',
      name: 'SomaFM Radio',
      description: 'Iconic commercial-free listener-supported radio channels (Groove Salad, Drone Zone, Secret Agent, DEF CON)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://somafm.com',
      timeoutMs: 1000,
      rateLimit: {
        maxRequests: 120,
        windowMs: 60000,
      },
      priority: 90,
      latencyClass: 'fast',
    },
    archivewatch: {
      id: 'archivewatch',
      name: 'Archive Watch (Prelinger Cinema)',
      description: 'Over 10,000 classic, public domain vintage films, cultural reels, retro commercials, and mid-century cinema',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    featurefilms: {
      id: 'featurefilms',
      name: 'Classic Feature Films',
      description: 'Over 25,000 full-length restored movies (Charlie Chaplin, Buster Keaton, Hitchcock, Film Noir, Horror & Westerns)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 87,
      latencyClass: 'fast',
    },
    classiccartoons: {
      id: 'classiccartoons',
      name: 'Classic Cartoons & Vintage Animation',
      description: 'Golden-era vintage animation reels (Fleischer Studios, Betty Boop, Popeye, Superman 1940s, Felix the Cat, Casper)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 87,
      latencyClass: 'fast',
    },
    nasasvs: {
      id: 'nasasvs',
      name: 'NASA Scientific Visualization Studio',
      description: 'Over 10,000 4K NASA space visualizations, astrophysics simulations, planetary flights & Earth climate models',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://svs.gsfc.nasa.gov',
      timeoutMs: 4000,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'medium',
    },
    tvnews: {
      id: 'tvnews',
      name: 'Global TV News Archive',
      description: 'Over 2 million historic broadcast television clips, network investigations, and world news journalism archives',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: false,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 84,
      latencyClass: 'fast',
    },
    computerchronicles: {
      id: 'computerchronicles',
      name: 'Computer Chronicles & Tech Vault',
      description: 'Historic computing TV episodes (1983–2002) showcasing early Apple, Silicon Graphics, Commodore Amiga & Internet pioneers',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 85,
      latencyClass: 'fast',
    },
    tedtalks: {
      id: 'tedtalks',
      name: 'TED & Open Culture',
      description: 'Inspirational TED Talks, technology lectures, science documentaries, and design ideas under Creative Commons (CC-BY-NC-ND)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'fast',
    },
    otradio: {
      id: 'otradio',
      name: 'Old Time Radio (OTR)',
      description: 'Golden Age vintage radio dramas (1930s-1950s: Sherlock Holmes, The Shadow, War of the Worlds, Dimension X, Suspense)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    prelinger: {
      id: 'prelinger',
      name: 'Prelinger Archives',
      description: 'Over 60,000 ephemeral historic films: mid-century Americana, atomic age educational reels, vintage automotive design & retro industry',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    freemusic: {
      id: 'freemusic',
      name: 'Free Music Archive & Open Audio',
      description: 'Royalty-free Creative Commons soundtracks, cinematic scores by Kevin MacLeod, ambient soundscapes, lo-fi, and independent musicians',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    coverr: {
      id: 'coverr',
      name: 'Coverr Free Stock Footage',
      description: 'Royalty-free cinematic 4K & HD stock video clips for creators, aerial drone shots, backgrounds, nature & urban loops',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: false,
      },
      baseUrl: 'https://coverr.co',
      timeoutMs: 600,
      rateLimit: {
        maxRequests: 120,
        windowMs: 60000,
      },
      priority: 92,
      latencyClass: 'fast',
    },
    scifihorror: {
      id: 'scifihorror',
      name: 'Sci-Fi & Horror Vault',
      description: 'Legendary sci-fi, cult horror, monster cinema, and vintage alien epics (Night of the Living Dead, Plan 9, House on Haunted Hill)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'fast',
    },
    silentfilms: {
      id: 'silentfilms',
      name: 'Silent Film Masters',
      description: 'Historic early cinema milestones & silent comedy masterpieces (Charlie Chaplin, Buster Keaton, Georges Méliès, Metropolis, Nosferatu)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'fast',
    },
    mitocw: {
      id: 'mitocw',
      name: 'MIT OpenCourseWare',
      description: 'World-class MIT university video lectures: Computer Science, Deep Learning, Linear Algebra, Physics, Algorithms & Engineering',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'fast',
    },
    animation: {
      id: 'animation',
      name: 'Golden Age Animation Vault',
      description: 'Historic vintage cartoons and hand-drawn animation milestones (Fleischer Studios, Popeye, Betty Boop, Superman 1941, Felix the Cat)',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 88,
      latencyClass: 'fast',
    },
    loc: {
      id: 'loc',
      name: 'Library of Congress',
      description: 'National Audiovisual Conservation Center: earliest motion pictures, historic newsreels, presidential addresses, San Francisco 1906',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    sportsarchive: {
      id: 'sportsarchive',
      name: 'Classic Sports & Olympics Vault',
      description: 'Legendary sporting milestones: Golden-age championship boxing (Muhammad Ali, Joe Louis, Frazier), historic Olympics & classic football',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    naturevids: {
      id: 'naturevids',
      name: 'Wildlife & Nature Vault',
      description: 'Expeditions into the wild: National parks, marine biology, coral reefs, African wildlife safaris, arctic glaciers, and botanical time-lapses',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 86,
      latencyClass: 'fast',
    },
    dvids: {
      id: 'dvids',
      name: 'DVIDS & Aerospace Media',
      description: 'Defense Visual Information Distribution Service — public domain aerospace missions, flight tests, naval engineering & historic expeditions',
      enabled: true,
      requiresKey: false,
      capabilities: {
        search: true,
        metadata: true,
        directPlayback: true,
        hls: false,
        embed: true,
      },
      baseUrl: 'https://archive.org',
      timeoutMs: 1600,
      rateLimit: {
        maxRequests: 60,
        windowMs: 60000,
      },
      priority: 85,
      latencyClass: 'fast',
    },
  };
}

export const providersConfig = getProvidersConfig();
